name: CI/CD with Versioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings

      - name: Bump version and push
        id: versioning
        run: |
          version=$(cat version.txt)
          echo "Current version: $version"

          major=$(echo $version | cut -d '.' -f 1)
          minor=$(echo $version | cut -d '.' -f 2)
          patch=$(echo $version | cut -d '.' -f 3)
          
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"

          echo $new_version > version.txt

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to $new_version"

      - name: Push changes
        run: |
          git push https://github.com/${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/rafael-branco/tricentis-automation-tests.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
