name: CI/CD with Versioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings

    - name: Bump version and push
      id: versioning
      run: |
        # Read the current version from version.txt
        version=$(cat version.txt)
        echo "Current version: $version"
        
        # Split the version into major, minor, and patch
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        # Increment the patch version
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        echo "New version: $new_version"
        
        # Write the new version back to version.txt
        echo $new_version > version.txt

        # Commit the new version and push it to the repository
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "Bump version to $new_version"
        git push origin main
